// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: api/proto/iot/up_msg.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DeviceUpMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId   uint32               `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ActionTime *timestamp.Timestamp `protobuf:"bytes,2,opt,name=action_time,json=actionTime,proto3" json:"action_time,omitempty"`
	// Types that are assignable to Payload:
	//	*DeviceUpMsg_LoginMsg
	//	*DeviceUpMsg_SetAttributesMsg
	//	*DeviceUpMsg_SetTelemetriesMsg
	//	*DeviceUpMsg_SetHealthMsg
	//	*DeviceUpMsg_CameraCaptureReplyMsg
	Payload isDeviceUpMsg_Payload `protobuf_oneof:"payload"`
}

func (x *DeviceUpMsg) Reset() {
	*x = DeviceUpMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_iot_up_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceUpMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceUpMsg) ProtoMessage() {}

func (x *DeviceUpMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_iot_up_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceUpMsg.ProtoReflect.Descriptor instead.
func (*DeviceUpMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_iot_up_msg_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceUpMsg) GetDeviceId() uint32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *DeviceUpMsg) GetActionTime() *timestamp.Timestamp {
	if x != nil {
		return x.ActionTime
	}
	return nil
}

func (m *DeviceUpMsg) GetPayload() isDeviceUpMsg_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *DeviceUpMsg) GetLoginMsg() *LoginMsg {
	if x, ok := x.GetPayload().(*DeviceUpMsg_LoginMsg); ok {
		return x.LoginMsg
	}
	return nil
}

func (x *DeviceUpMsg) GetSetAttributesMsg() *SetAttributesMsg {
	if x, ok := x.GetPayload().(*DeviceUpMsg_SetAttributesMsg); ok {
		return x.SetAttributesMsg
	}
	return nil
}

func (x *DeviceUpMsg) GetSetTelemetriesMsg() *SetTelemetriesMsg {
	if x, ok := x.GetPayload().(*DeviceUpMsg_SetTelemetriesMsg); ok {
		return x.SetTelemetriesMsg
	}
	return nil
}

func (x *DeviceUpMsg) GetSetHealthMsg() *SetHealthMsg {
	if x, ok := x.GetPayload().(*DeviceUpMsg_SetHealthMsg); ok {
		return x.SetHealthMsg
	}
	return nil
}

func (x *DeviceUpMsg) GetCameraCaptureReplyMsg() *CameraCaptureReplyMsg {
	if x, ok := x.GetPayload().(*DeviceUpMsg_CameraCaptureReplyMsg); ok {
		return x.CameraCaptureReplyMsg
	}
	return nil
}

type isDeviceUpMsg_Payload interface {
	isDeviceUpMsg_Payload()
}

type DeviceUpMsg_LoginMsg struct {
	LoginMsg *LoginMsg `protobuf:"bytes,3,opt,name=login_msg,json=loginMsg,proto3,oneof"`
}

type DeviceUpMsg_SetAttributesMsg struct {
	SetAttributesMsg *SetAttributesMsg `protobuf:"bytes,4,opt,name=set_attributes_msg,json=setAttributesMsg,proto3,oneof"`
}

type DeviceUpMsg_SetTelemetriesMsg struct {
	SetTelemetriesMsg *SetTelemetriesMsg `protobuf:"bytes,5,opt,name=set_telemetries_msg,json=setTelemetriesMsg,proto3,oneof"`
}

type DeviceUpMsg_SetHealthMsg struct {
	SetHealthMsg *SetHealthMsg `protobuf:"bytes,6,opt,name=set_health_msg,json=setHealthMsg,proto3,oneof"`
}

type DeviceUpMsg_CameraCaptureReplyMsg struct {
	CameraCaptureReplyMsg *CameraCaptureReplyMsg `protobuf:"bytes,7,opt,name=camera_capture_reply_msg,json=cameraCaptureReplyMsg,proto3,oneof"`
}

func (*DeviceUpMsg_LoginMsg) isDeviceUpMsg_Payload() {}

func (*DeviceUpMsg_SetAttributesMsg) isDeviceUpMsg_Payload() {}

func (*DeviceUpMsg_SetTelemetriesMsg) isDeviceUpMsg_Payload() {}

func (*DeviceUpMsg_SetHealthMsg) isDeviceUpMsg_Payload() {}

func (*DeviceUpMsg_CameraCaptureReplyMsg) isDeviceUpMsg_Payload() {}

type LoginMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessKey string `protobuf:"bytes,1,opt,name=accessKey,proto3" json:"accessKey,omitempty"`
	SecretKey string `protobuf:"bytes,2,opt,name=secretKey,proto3" json:"secretKey,omitempty"`
}

func (x *LoginMsg) Reset() {
	*x = LoginMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_iot_up_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginMsg) ProtoMessage() {}

func (x *LoginMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_iot_up_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginMsg.ProtoReflect.Descriptor instead.
func (*LoginMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_iot_up_msg_proto_rawDescGZIP(), []int{1}
}

func (x *LoginMsg) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *LoginMsg) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

type SetAttributesMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttributeMap map[uint32]string `protobuf:"bytes,1,rep,name=attribute_map,json=attributeMap,proto3" json:"attribute_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SetAttributesMsg) Reset() {
	*x = SetAttributesMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_iot_up_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetAttributesMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAttributesMsg) ProtoMessage() {}

func (x *SetAttributesMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_iot_up_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAttributesMsg.ProtoReflect.Descriptor instead.
func (*SetAttributesMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_iot_up_msg_proto_rawDescGZIP(), []int{2}
}

func (x *SetAttributesMsg) GetAttributeMap() map[uint32]string {
	if x != nil {
		return x.AttributeMap
	}
	return nil
}

type SetTelemetriesMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TelemetryMap map[uint32]float64 `protobuf:"bytes,1,rep,name=telemetry_map,json=telemetryMap,proto3" json:"telemetry_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
}

func (x *SetTelemetriesMsg) Reset() {
	*x = SetTelemetriesMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_iot_up_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetTelemetriesMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTelemetriesMsg) ProtoMessage() {}

func (x *SetTelemetriesMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_iot_up_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTelemetriesMsg.ProtoReflect.Descriptor instead.
func (*SetTelemetriesMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_iot_up_msg_proto_rawDescGZIP(), []int{3}
}

func (x *SetTelemetriesMsg) GetTelemetryMap() map[uint32]float64 {
	if x != nil {
		return x.TelemetryMap
	}
	return nil
}

type SetHealthMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceHealth uint32 `protobuf:"varint,1,opt,name=device_health,json=deviceHealth,proto3" json:"device_health,omitempty"`
}

func (x *SetHealthMsg) Reset() {
	*x = SetHealthMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_iot_up_msg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetHealthMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHealthMsg) ProtoMessage() {}

func (x *SetHealthMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_iot_up_msg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHealthMsg.ProtoReflect.Descriptor instead.
func (*SetHealthMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_iot_up_msg_proto_rawDescGZIP(), []int{4}
}

func (x *SetHealthMsg) GetDeviceHealth() uint32 {
	if x != nil {
		return x.DeviceHealth
	}
	return 0
}

type CameraCaptureReplyMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subject string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Ok      bool   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *CameraCaptureReplyMsg) Reset() {
	*x = CameraCaptureReplyMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_iot_up_msg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CameraCaptureReplyMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraCaptureReplyMsg) ProtoMessage() {}

func (x *CameraCaptureReplyMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_iot_up_msg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraCaptureReplyMsg.ProtoReflect.Descriptor instead.
func (*CameraCaptureReplyMsg) Descriptor() ([]byte, []int) {
	return file_api_proto_iot_up_msg_proto_rawDescGZIP(), []int{5}
}

func (x *CameraCaptureReplyMsg) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CameraCaptureReplyMsg) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_api_proto_iot_up_msg_proto protoreflect.FileDescriptor

var file_api_proto_iot_up_msg_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6f, 0x74, 0x2f,
	0x75, 0x70, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xbe, 0x03, 0x0a, 0x0b, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x55, 0x70, 0x4d, 0x73,
	0x67, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x3b,
	0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x0a, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x09, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4d, 0x73, 0x67, 0x48, 0x00, 0x52, 0x08,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x4d, 0x73, 0x67, 0x12, 0x44, 0x0a, 0x12, 0x73, 0x65, 0x74, 0x5f,
	0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x4d, 0x73, 0x67, 0x48, 0x00, 0x52, 0x10, 0x73, 0x65,
	0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x4d, 0x73, 0x67, 0x12, 0x47,
	0x0a, 0x13, 0x73, 0x65, 0x74, 0x5f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x65, 0x74, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x65, 0x73, 0x4d,
	0x73, 0x67, 0x48, 0x00, 0x52, 0x11, 0x73, 0x65, 0x74, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x4d, 0x73, 0x67, 0x12, 0x38, 0x0a, 0x0e, 0x73, 0x65, 0x74, 0x5f, 0x68,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x74, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x4d, 0x73,
	0x67, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x65, 0x74, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x4d, 0x73,
	0x67, 0x12, 0x54, 0x0a, 0x18, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x5f, 0x63, 0x61, 0x70, 0x74,
	0x75, 0x72, 0x65, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x43,
	0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x4d, 0x73, 0x67, 0x48, 0x00,
	0x52, 0x15, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x4d, 0x73, 0x67, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x22, 0x46, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4d, 0x73, 0x67, 0x12, 0x1c,
	0x0a, 0x09, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x22, 0xa0, 0x01, 0x0a, 0x10, 0x53,
	0x65, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x4d, 0x73, 0x67, 0x12,
	0x4b, 0x0a, 0x0d, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x6d, 0x61, 0x70,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x74, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x4d, 0x73, 0x67, 0x2e, 0x41, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c,
	0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x4d, 0x61, 0x70, 0x1a, 0x3f, 0x0a, 0x11,
	0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xa2, 0x01,
	0x0a, 0x11, 0x53, 0x65, 0x74, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x65, 0x73,
	0x4d, 0x73, 0x67, 0x12, 0x4c, 0x0a, 0x0d, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79,
	0x5f, 0x6d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x70, 0x62, 0x2e,
	0x53, 0x65, 0x74, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x65, 0x73, 0x4d, 0x73,
	0x67, 0x2e, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x4d, 0x61, 0x70, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x0c, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x4d, 0x61,
	0x70, 0x1a, 0x3f, 0x0a, 0x11, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x4d, 0x61,
	0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x33, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x4d,
	0x73, 0x67, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x68, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x22, 0x41, 0x0a, 0x15, 0x43, 0x61, 0x6d, 0x65, 0x72,
	0x61, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x4d, 0x73, 0x67,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_iot_up_msg_proto_rawDescOnce sync.Once
	file_api_proto_iot_up_msg_proto_rawDescData = file_api_proto_iot_up_msg_proto_rawDesc
)

func file_api_proto_iot_up_msg_proto_rawDescGZIP() []byte {
	file_api_proto_iot_up_msg_proto_rawDescOnce.Do(func() {
		file_api_proto_iot_up_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_iot_up_msg_proto_rawDescData)
	})
	return file_api_proto_iot_up_msg_proto_rawDescData
}

var file_api_proto_iot_up_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_iot_up_msg_proto_goTypes = []interface{}{
	(*DeviceUpMsg)(nil),           // 0: pb.DeviceUpMsg
	(*LoginMsg)(nil),              // 1: pb.LoginMsg
	(*SetAttributesMsg)(nil),      // 2: pb.SetAttributesMsg
	(*SetTelemetriesMsg)(nil),     // 3: pb.SetTelemetriesMsg
	(*SetHealthMsg)(nil),          // 4: pb.SetHealthMsg
	(*CameraCaptureReplyMsg)(nil), // 5: pb.CameraCaptureReplyMsg
	nil,                           // 6: pb.SetAttributesMsg.AttributeMapEntry
	nil,                           // 7: pb.SetTelemetriesMsg.TelemetryMapEntry
	(*timestamp.Timestamp)(nil),   // 8: google.protobuf.Timestamp
}
var file_api_proto_iot_up_msg_proto_depIdxs = []int32{
	8, // 0: pb.DeviceUpMsg.action_time:type_name -> google.protobuf.Timestamp
	1, // 1: pb.DeviceUpMsg.login_msg:type_name -> pb.LoginMsg
	2, // 2: pb.DeviceUpMsg.set_attributes_msg:type_name -> pb.SetAttributesMsg
	3, // 3: pb.DeviceUpMsg.set_telemetries_msg:type_name -> pb.SetTelemetriesMsg
	4, // 4: pb.DeviceUpMsg.set_health_msg:type_name -> pb.SetHealthMsg
	5, // 5: pb.DeviceUpMsg.camera_capture_reply_msg:type_name -> pb.CameraCaptureReplyMsg
	6, // 6: pb.SetAttributesMsg.attribute_map:type_name -> pb.SetAttributesMsg.AttributeMapEntry
	7, // 7: pb.SetTelemetriesMsg.telemetry_map:type_name -> pb.SetTelemetriesMsg.TelemetryMapEntry
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_iot_up_msg_proto_init() }
func file_api_proto_iot_up_msg_proto_init() {
	if File_api_proto_iot_up_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_iot_up_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceUpMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_iot_up_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_iot_up_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetAttributesMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_iot_up_msg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetTelemetriesMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_iot_up_msg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetHealthMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_iot_up_msg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CameraCaptureReplyMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_proto_iot_up_msg_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*DeviceUpMsg_LoginMsg)(nil),
		(*DeviceUpMsg_SetAttributesMsg)(nil),
		(*DeviceUpMsg_SetTelemetriesMsg)(nil),
		(*DeviceUpMsg_SetHealthMsg)(nil),
		(*DeviceUpMsg_CameraCaptureReplyMsg)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_iot_up_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_iot_up_msg_proto_goTypes,
		DependencyIndexes: file_api_proto_iot_up_msg_proto_depIdxs,
		MessageInfos:      file_api_proto_iot_up_msg_proto_msgTypes,
	}.Build()
	File_api_proto_iot_up_msg_proto = out.File
	file_api_proto_iot_up_msg_proto_rawDesc = nil
	file_api_proto_iot_up_msg_proto_goTypes = nil
	file_api_proto_iot_up_msg_proto_depIdxs = nil
}
