FROM 9d77v/pdc-base:0.0.8
COPY . /app

ENV APP_NAME=pdc-device-esp8266
RUN cd /app \
    && go build  -o $APP_NAME -ldflags "-s -w" iot/esp8266/main.go \
    && upx -9 $APP_NAME

FROM scratch
ENV APP_NAME=pdc-device-esp8266
COPY --from=0  /app/$APP_NAME /usr/bin/$APP_NAME

WORKDIR /app
CMD [ "pdc-device-esp8266" ]