FROM golang:1.14.2-alpine3.11

WORKDIR /app
ENV CGO_ENABLED 0
ENV GO111MODULE on
ENV GOPROXY=https://goproxy.cn

RUN echo "http://mirrors.aliyun.com/alpine/v3.11/main/" > /etc/apk/repositories \
    && echo "http://mirrors.aliyun.com/alpine/v3.11/community/" >> /etc/apk/repositories \
    && apk add --no-cache upx

COPY go.mod /app
COPY go.sum /app

RUN go mod download \
    && rm -rf /app

