version: '3.6'

services:
  minio:
    image: 9d77v/minio:arm64.2020-04-12
    restart: always
    volumes:
      - ./minio/data:/data
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123 
    command: minio server /data
    container_name: minio
  clickhouse-server:
    image: 9d77v/clickhouse-server:arm64.2020-09-05
    restart: always
    volumes: 
      - ./clickhouse/data:/var/lib/clickhouse
      # - ./clickhouse/config.xml:/ClickHouse/config.xml
      # - ./clickhouse/users.mxl:/ClickHouse/users.xml
    ports:
      - 9001:9000
    container_name: clickhouse-server
  nats-streaming:
    image: nats-streaming:0.18.0-alpine3.12
    restart: always
    ports:
      - 4222:4222
      - 8222:8222
    container_name: nats-streaming
  elasticsearch:
    image: 9d77v/elasticsearch:7.8.1
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./configs/elasticsearch/analysis-ik/custom:/usr/share/elasticsearch/config/analysis-ik/custom
      - ./configs/elasticsearch/analysis:/usr/share/elasticsearch/config/analysis
    container_name: elasticsearch
  db:
    image: postgres:12.1-alpine
    restart: always
    user: root
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    container_name: db
  redis:
    image: redis:6.0.5-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
    volumes:
        - ./redis/data:/data
    container_name: redis
  pdc:
    image: 9d77v/pdc:2020-12-18_e912ad2
    restart: always
    ports: 
      - 8080:8080
    env_file:
      - ./configs/pdc.env
    container_name: pdc
  # pdc-iot-esp8266-sht3x:
  #   image: 9d77v/pdc-iot-esp8266-sht3x:2020-12-14_9ad545b
  #   restart: always
  #   env_file:
  #     - esp8266-sht3x.env
  #   container_name: pdc-iot-esp8266-sht3x
  # pdc-iot-raspi:
  #   image: 9d77v/pdc-iot-raspi:2020-12-14_9ad545b
  #   restart: always
  #   env_file:
  #     - raspi.env
  #   devices:
  #     - /dev/i2c-0
  #     - /dev/i2c-1  
  #   container_name: pdc-iot-raspi
  # pdc-iot-camera:
  #   image: 9d77v/pdc-iot-camera:2020-12-14_9ad545b
  #   restart: always
  #   env_file:
  #     - camera.env
  #   container_name: pdc-iot-camera
  # pdc-cron-camera:
  #   image: 9d77v/pdc-cron-camera:2020-12-14_9ad545b
  #   restart: always
  #   env_file:
  #     - pdc.env
  #   container_name: pdc-cron-camera
  # ffmpeg:
  #   image: linuxserver/ffmpeg:4.3-cli-ls43
  #   restart: always
  #   network_mode: host
  #   command: -rtsp_transport tcp -i rtsp://[username]:[password]@[rtsp_ip]:554/Streaming/Channels/101 -f mp4 -vcodec copy  -an -f flv -an rtmp://[nginx_ip]:1935/live/stream1
  #   container_name: ffmpeg
  # nginx-rtmp-hls:
  #   image: 9d77v/nginx-rtmp-hls:1.19.4-1.2.1
  #   ports:
  #     - 1935:1935
  #     - 8080:8080
  #   container_name: nginx-rtmp-hls
  caddy:
    image: 9d77v/caddy:2.1.1-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    user: root
    environment:
      - TZ=Asia/Shanghai
      - ALICLOUD_ACCESS_KEY=
      - ALICLOUD_SECRET_KEY=
    volumes:
      - ./configs/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./configs/caddy/config:/config/caddy
      - ./configs/caddy/data:/data/caddy
    container_name: caddy
