FROM 9d77v/pdc-base:0.0.9
COPY . /app

ENV APP_NAME=pdc-device-raspi
RUN cd /app \
    && go build  -o $APP_NAME -ldflags "-s -w" iot/raspi/main.go \
    && upx -9 $APP_NAME

FROM scratch
ENV APP_NAME=pdc-device-raspi
COPY --from=0  /app/$APP_NAME /usr/bin/$APP_NAME

WORKDIR /app
CMD [ "pdc-device-raspi" ]
