FROM alpine:3.12

RUN echo "http://mirrors.aliyun.com/alpine/v3.11/main/" > /etc/apk/repositories \
    && echo "http://mirrors.aliyun.com/alpine/v3.11/community/" >> /etc/apk/repositories \
    && apk add --no-cache ca-certificates
