#!/bin/sh
app='pdc'
version="0.0.8"
sudo=""
if command -v sudo >/dev/null 2>&1; then
    sudo="sudo"
fi

case $1 in 
    gen)
        go generate ./...
        ;;
    dev)
        go run server.go
        ;;
    ui)
        cd ui
        yarn start
        ;;
    base)
        $sudo docker build -t 9d77v/$app-base:$version -f Dockerfile.base .
        $sudo docker push 9d77v/$app-base:$version
       ;;
    deploy)
        # cd ui 
        # yarn build
        # cd ..
        IMAGE_TAG=`git log --pretty=format:"%ad_%h" -1 --date=short`
        echo "build pdc"
        $sudo docker build -t 9d77v/$app:$IMAGE_TAG .
        $sudo docker push 9d77v/$app:$IMAGE_TAG
        ;;
    esp8266)
        IMAGE_TAG=`git log --pretty=format:"%ad_%h" -1 --date=short`
        echo "build pdc-device-esp8266"
        $sudo docker build -t 9d77v/pdc-device-esp8266:$IMAGE_TAG -f Dockerfile.esp8266 .
        $sudo docker push 9d77v/pdc-device-esp8266:$IMAGE_TAG   
        ;;
esac  

