#!/bin/sh
app='pdc'
version="0.0.11"
base_deploy_version="0.0.1"
sudo=""
if command -v sudo >/dev/null 2>&1; then
    sudo="sudo"
fi

case $1 in 
    gen)
        go generate ./...
        ;;
    dev)
        go run server.go
        ;;
    ui)
        cd ui
        yarn start
        ;;
    b|backup)
        datename=$(date +%Y%m%d)
        PGPASSWORD="123456" pg_dump -h domain.local -p 5432 -U postgres  -d pdc -f ./pdc_db_backup.$datename.tar.gz -Ft 
        ;;
    base)
        $sudo docker build -t 9d77v/$app-base:$version -f Dockerfile.base .
        $sudo docker push 9d77v/$app-base:$version
       ;;
    base-deploy)
        $sudo docker build -t 9d77v/$app-base-deploy:$base_deploy_version -f Dockerfile.base.deploy .
        $sudo docker push 9d77v/$app-base-deploy:$base_deploy_version
       ;;
    deploy)
        # cd ui 
        # yarn build
        # cd ..
        IMAGE_TAG=`git log --pretty=format:"%ad_%h" -1 --date=short`
        echo "build pdc"
        $sudo docker build -t 9d77v/$app:$IMAGE_TAG .
        $sudo docker push 9d77v/$app:$IMAGE_TAG
        ;;
    esp8266-sht3x)
        IMAGE_TAG=`git log --pretty=format:"%ad_%h" -1 --date=short`
        echo "build pdc-device-esp8266-sht3x"
        $sudo docker build -t 9d77v/pdc-device-esp8266-sht3x:$IMAGE_TAG -f Dockerfile.esp8266.sht3x .
        $sudo docker push 9d77v/pdc-device-esp8266-sht3x:$IMAGE_TAG   
        ;;
    raspi)
        IMAGE_TAG=`git log --pretty=format:"%ad_%h" -1 --date=short`
        echo "build pdc-device-raspi"
        $sudo docker build -t 9d77v/pdc-device-raspi:$IMAGE_TAG -f Dockerfile.raspi .
        $sudo docker push 9d77v/pdc-device-raspi:$IMAGE_TAG   
        ;;
    gosec)
       gosec -exclude=G204 -conf gosec.json ./...
       ;;
esac  

