const AppPath = {
    HOME: "/app/home",
    DEVICE: "/app/device",
    DEVICE_TELEMETRY: "/app/device/telemetry",
    DEVICE_CAMERA: "/app/device/camera",
    DEVICE_CAMERA_DETAIL: "/app/device/camera/detail",
    VIDEO: "/app/video",
    VIDEO_DETAIL: "/app/video/detail",
    VIDEO_SUGGEST: "/app/video/suggest",
    VIDEO_SEARCH: "/app/video/search",
    HISTORY: "/app/history",
    THING: "/app/thing",
    THING_LIST: "/app/thing/things",
    THING_DASHBOARD: "/app/thing/dashboard",
    THING_ANALYSIS: "/app/thing/analysis",
    USER: "/app/user",
    USER_PROFILE: "/app/user/profile",
    USER_ACCOUNT: "/app/user/account",
    USER_DATA_ANALYSIS: "/app/user/data_analysis",
    USER_GESTURE_PASSWORD: "/app/user/gesture_password",
    UESR_QECODE: "/app/user/qrcode",
    SCANNER: "/app/scanner",
    GESTURE_LOGIN: "/gesture_login",
    LOGIN: "/login",
    CONTACT_ADD: "/app/contact/addContact",
    UTIL: "/app/util",
    UTIL_CALCULATOR: "/app/util/calculator",
    UTIL_NOTE: "/app/util/note",
    MSG: "/app/msg"
}

const AdminPath = {
    HOME: "/admin/home",
    VIDEO: "/admin/video",
    VIDEO_LIST: "/admin/video/video-list",
    VIDEO_CREATE: "/admin/video/video-list/video-create",
    VIDEO_SEREIS_LIST: "/admin/video/video-series-list",
    VIDEO_DATA_ANALYSIS: "/admin/video/data_analysis",
    DEVICE: "/admin/device",
    DEVICE_MODEL_LIST: "/admin/device/device-model-list",
    DEVICE_DASHBOARD_LIST: "/admin/device/device-dashboard-list",
    DEVICE_LIST: "/admin/device/device-list",
    BOOK: "/admin/book",
    BOOK_LIST: "/admin/book/book-list",
    BOOKSHELF_LIST: "/admin/book/bookshelf-list",
    BOOK_BORROW_RETURN_LIST: "/admin/book/book-borrow-return-list",
    USER: "/admin/user",
    USER_LIST: "/admin/user/user-list"
}

const PathDict = new Map<string, string>([
    [AppPath.HOME, '首页'],
    [AppPath.DEVICE, '设备'],
    [AppPath.DEVICE_TELEMETRY, '遥测'],
    [AppPath.DEVICE_CAMERA, '摄像头'],
    [AppPath.USER, '个人主页'],
    [AppPath.USER_PROFILE, '个人资料'],
    [AppPath.USER_ACCOUNT, '账户安全'],
    [AppPath.USER_DATA_ANALYSIS, '数据统计'],
    [AppPath.HISTORY, '最近播放'],
    [AppPath.VIDEO, '视频'],
    [AppPath.VIDEO_SUGGEST, '视频推荐'],
    [AppPath.VIDEO_SEARCH, '视频索引'],
    [AppPath.VIDEO_DETAIL, '视频页'],
    [AppPath.THING, '物品'],
    [AppPath.THING_DASHBOARD, '物品概览'],
    [AppPath.THING_LIST, '物品列表'],
    [AppPath.THING_ANALYSIS, '物品分析'],
    [AppPath.UTIL, '工具'],
    [AppPath.UTIL_NOTE, '记事本'],
    [AppPath.UTIL_CALCULATOR, '计算器'],
    [AdminPath.HOME, '首页'],
    [AdminPath.VIDEO, '视频管理'],
    [AdminPath.VIDEO_LIST, '视频列表'],
    [AdminPath.VIDEO_CREATE, '新增视频'],
    [AdminPath.VIDEO_SEREIS_LIST, '视频系列列表'],
    [AdminPath.VIDEO_DATA_ANALYSIS, '视频数据分析'],
    [AdminPath.DEVICE, '设备管理'],
    [AdminPath.DEVICE_LIST, '设备列表'],
    [AdminPath.DEVICE_MODEL_LIST, '设备模板列表'],
    [AdminPath.DEVICE_DASHBOARD_LIST, '设备仪表盘'],
    [AdminPath.BOOK, '书籍管理'],
    [AdminPath.BOOK_LIST, '书籍列表'],
    [AdminPath.BOOKSHELF_LIST, '书架列表'],
    [AdminPath.BOOK_BORROW_RETURN_LIST, '书籍借还列表'],
    [AdminPath.USER, '用户管理'],
    [AdminPath.USER_LIST, '用户列表'],
])

export { AppPath, AdminPath, PathDict }
