// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Character struct {
	CharacterName string `json:"characterName"`
	OriginalName  string `json:"originalName"`
}

type Episode struct {
	ID        int64       `json:"id"`
	VideoID   int64       `json:"videoID"`
	Num       float64     `json:"num"`
	Title     string      `json:"title"`
	Desc      string      `json:"desc"`
	Cover     string      `json:"cover"`
	URL       string      `json:"url"`
	Subtitles []*Subtitle `json:"subtitles"`
	CreatedAt int64       `json:"createdAt"`
	UpdatedAt int64       `json:"updatedAt"`
}

type NewCharacter struct {
	CharacterName string `json:"characterName"`
	OriginalName  string `json:"originalName"`
}

type NewEpisode struct {
	VideoID   int64          `json:"videoID"`
	Num       float64        `json:"num"`
	Title     *string        `json:"title"`
	Desc      *string        `json:"desc"`
	Cover     *string        `json:"cover"`
	URL       string         `json:"url"`
	Subtitles []*NewSubtitle `json:"subtitles"`
}

type NewStaff struct {
	Job     string   `json:"job"`
	Persons []string `json:"persons"`
}

type NewSubtitle struct {
	Name string `json:"name"`
	URL  string `json:"url"`
}

type NewSubtitles struct {
	Name string   `json:"name"`
	Urls []string `json:"urls"`
}

type NewThing struct {
	Name                string   `json:"name"`
	Num                 float64  `json:"num"`
	BrandName           *string  `json:"brandName"`
	Pics                []string `json:"pics"`
	UnitPrice           float64  `json:"unitPrice"`
	Unit                *string  `json:"unit"`
	Specifications      *string  `json:"specifications"`
	Category            int64    `json:"category"`
	ConsumerExpenditure string   `json:"consumerExpenditure"`
	Location            *string  `json:"location"`
	Status              int64    `json:"status"`
	PurchaseDate        int64    `json:"purchaseDate"`
	PurchasePlatform    *string  `json:"purchasePlatform"`
	RefOrderID          *string  `json:"refOrderID"`
	RubbishCategory     []int64  `json:"rubbishCategory"`
}

type NewUpdateEpisode struct {
	ID        int64          `json:"id"`
	Num       *float64       `json:"num"`
	Title     *string        `json:"title"`
	Desc      *string        `json:"desc"`
	Cover     *string        `json:"cover"`
	URL       string         `json:"url"`
	Subtitles []*NewSubtitle `json:"subtitles"`
}

type NewUpdateThing struct {
	ID                  int64    `json:"id"`
	Name                *string  `json:"name"`
	Num                 *float64 `json:"num"`
	BrandName           *string  `json:"brandName"`
	Pics                []string `json:"pics"`
	UnitPrice           *float64 `json:"unitPrice"`
	Unit                *string  `json:"unit"`
	Specifications      *string  `json:"specifications"`
	Category            *int64   `json:"category"`
	ConsumerExpenditure *string  `json:"consumerExpenditure"`
	Location            *string  `json:"location"`
	Status              *int64   `json:"status"`
	PurchaseDate        *int64   `json:"purchaseDate"`
	PurchasePlatform    *string  `json:"purchasePlatform"`
	RefOrderID          *string  `json:"refOrderID"`
	RubbishCategory     []int64  `json:"rubbishCategory"`
}

type NewUpdateUser struct {
	ID        int64   `json:"id"`
	Password  *string `json:"password"`
	Avatar    *string `json:"avatar"`
	RoleID    *int64  `json:"roleID"`
	Gender    *int64  `json:"gender"`
	Color     *string `json:"color"`
	BirthDate *int64  `json:"birthDate"`
	IP        *string `json:"ip"`
}

type NewUpdateVideo struct {
	ID         int64           `json:"id"`
	Title      *string         `json:"title"`
	Desc       *string         `json:"desc"`
	PubDate    *int64          `json:"pubDate"`
	Cover      *string         `json:"cover"`
	Characters []*NewCharacter `json:"characters"`
	Staffs     []*NewStaff     `json:"staffs"`
	Tags       []string        `json:"tags"`
	IsShow     *bool           `json:"isShow"`
}

type NewUser struct {
	Name      string  `json:"name"`
	Password  string  `json:"password"`
	Avatar    *string `json:"avatar"`
	RoleID    int64   `json:"roleID"`
	Gender    int64   `json:"gender"`
	BirthDate *int64  `json:"birthDate"`
	IP        *string `json:"ip"`
}

type NewVideo struct {
	Title      string          `json:"title"`
	Desc       *string         `json:"desc"`
	PubDate    *int64          `json:"pubDate"`
	Cover      *string         `json:"cover"`
	Characters []*NewCharacter `json:"characters"`
	Staffs     []*NewStaff     `json:"staffs"`
	Tags       []string        `json:"tags"`
	IsShow     bool            `json:"isShow"`
	VideoURLs  []string        `json:"videoURLs"`
	Subtitles  *NewSubtitles   `json:"subtitles"`
}

type PieLineSerieData struct {
	X1 []string  `json:"x1"`
	X2 []string  `json:"x2"`
	Y  []float64 `json:"y"`
}

type SerieData struct {
	Name  string  `json:"name"`
	Value float64 `json:"value"`
}

type Sort struct {
	Field string `json:"field"`
	IsAsc bool   `json:"isAsc"`
}

type Staff struct {
	Job     string   `json:"Job"`
	Persons []string `json:"Persons"`
}

type Subtitle struct {
	Name string `json:"name"`
	URL  string `json:"url"`
}

type Thing struct {
	ID                  int64    `json:"id"`
	UID                 int64    `json:"uid"`
	Name                string   `json:"name"`
	Num                 float64  `json:"num"`
	BrandName           *string  `json:"brandName"`
	Pics                []string `json:"pics"`
	UnitPrice           float64  `json:"unitPrice"`
	Unit                *string  `json:"unit"`
	Specifications      *string  `json:"specifications"`
	Category            int64    `json:"category"`
	ConsumerExpenditure string   `json:"consumerExpenditure"`
	Location            string   `json:"location"`
	Status              int64    `json:"status"`
	PurchaseDate        int64    `json:"purchaseDate"`
	PurchasePlatform    *string  `json:"purchasePlatform"`
	RefOrderID          string   `json:"refOrderID"`
	RubbishCategory     []int64  `json:"rubbishCategory"`
	CreatedAt           int64    `json:"createdAt"`
	UpdatedAt           int64    `json:"updatedAt"`
}

type ThingConnection struct {
	TotalCount int64    `json:"totalCount"`
	Edges      []*Thing `json:"edges"`
}

type User struct {
	ID        int64   `json:"id"`
	Name      string  `json:"name"`
	Avatar    *string `json:"avatar"`
	RoleID    int64   `json:"roleID"`
	Gender    int64   `json:"gender"`
	Color     *string `json:"color"`
	BirthDate int64   `json:"birthDate"`
	IP        *string `json:"ip"`
	CreatedAt int64   `json:"createdAt"`
	UpdatedAt int64   `json:"updatedAt"`
}

type UserConnection struct {
	TotalCount int64   `json:"totalCount"`
	Edges      []*User `json:"edges"`
}

type Video struct {
	ID         int64        `json:"id"`
	Title      string       `json:"title"`
	Desc       string       `json:"desc"`
	PubDate    int64        `json:"pubDate"`
	Cover      string       `json:"cover"`
	Episodes   []*Episode   `json:"episodes"`
	Characters []*Character `json:"characters"`
	Staffs     []*Staff     `json:"staffs"`
	Tags       []string     `json:"tags"`
	IsShow     bool         `json:"isShow"`
	CreatedAt  int64        `json:"createdAt"`
	UpdatedAt  int64        `json:"updatedAt"`
}

type VideoConnection struct {
	TotalCount int64    `json:"totalCount"`
	Edges      []*Video `json:"edges"`
}
