// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AggResult struct {
	Key   string `json:"key"`
	Value int64  `json:"value"`
}

type Attribute struct {
	ID        int64  `json:"id"`
	DeviceID  int64  `json:"deviceID"`
	Key       string `json:"key"`
	Name      string `json:"name"`
	Value     string `json:"value"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
}

type AttributeModel struct {
	ID            int64  `json:"id"`
	DeviceModelID int64  `json:"deviceModelID"`
	Key           string `json:"key"`
	Name          string `json:"name"`
	CreatedAt     int64  `json:"createdAt"`
	UpdatedAt     int64  `json:"updatedAt"`
}

type Character struct {
	CharacterName string `json:"characterName"`
	OriginalName  string `json:"originalName"`
}

type Device struct {
	ID                       int64        `json:"id"`
	DeviceModelID            int64        `json:"deviceModelID"`
	Name                     string       `json:"name"`
	IP                       string       `json:"ip"`
	Port                     int64        `json:"port"`
	AccessKey                string       `json:"accessKey"`
	SecretKey                string       `json:"secretKey"`
	DeviceModelName          string       `json:"deviceModelName"`
	DeviceModelDesc          string       `json:"deviceModelDesc"`
	DeviceModelDeviceType    int64        `json:"deviceModelDeviceType"`
	DeviceModelCameraCompany int64        `json:"deviceModelCameraCompany"`
	Attributes               []*Attribute `json:"attributes"`
	Telemetries              []*Telemetry `json:"telemetries"`
	Username                 string       `json:"username"`
	Password                 string       `json:"password"`
	CreatedAt                int64        `json:"createdAt"`
	UpdatedAt                int64        `json:"updatedAt"`
}

type DeviceConnection struct {
	TotalCount int64     `json:"totalCount"`
	Edges      []*Device `json:"edges"`
}

type DeviceDashboard struct {
	ID          int64                       `json:"id"`
	Name        string                      `json:"name"`
	IsVisible   bool                        `json:"isVisible"`
	DeviceType  int64                       `json:"deviceType"`
	Telemetries []*DeviceDashboardTelemetry `json:"telemetries"`
	Cameras     []*DeviceDashboardCamera    `json:"cameras"`
	CreatedAt   int64                       `json:"createdAt"`
	UpdatedAt   int64                       `json:"updatedAt"`
}

type DeviceDashboardCamera struct {
	ID                int64  `json:"id"`
	DeviceDashboardID int64  `json:"deviceDashboardID"`
	DeviceID          int64  `json:"deviceID"`
	DeviceName        string `json:"deviceName"`
	CreatedAt         int64  `json:"createdAt"`
	UpdatedAt         int64  `json:"updatedAt"`
}

type DeviceDashboardConnection struct {
	TotalCount int64              `json:"totalCount"`
	Edges      []*DeviceDashboard `json:"edges"`
}

type DeviceDashboardTelemetry struct {
	ID                int64    `json:"id"`
	DeviceDashboardID int64    `json:"deviceDashboardID"`
	DeviceID          int64    `json:"deviceID"`
	DeviceName        string   `json:"deviceName"`
	TelemetryID       int64    `json:"telemetryID"`
	Key               string   `json:"key"`
	Name              string   `json:"name"`
	Value             *float64 `json:"value"`
	Factor            float64  `json:"factor"`
	Scale             int64    `json:"scale"`
	Unit              string   `json:"unit"`
	UnitName          string   `json:"unitName"`
	CreatedAt         int64    `json:"createdAt"`
	UpdatedAt         int64    `json:"updatedAt"`
}

type DeviceModel struct {
	ID              int64             `json:"id"`
	Name            string            `json:"name"`
	DeviceType      int64             `json:"deviceType"`
	Desc            string            `json:"desc"`
	AttributeModels []*AttributeModel `json:"attributeModels"`
	TelemetryModels []*TelemetryModel `json:"telemetryModels"`
	CameraCompany   int64             `json:"cameraCompany"`
	CreatedAt       int64             `json:"createdAt"`
	UpdatedAt       int64             `json:"updatedAt"`
}

type DeviceModelConnection struct {
	TotalCount int64          `json:"totalCount"`
	Edges      []*DeviceModel `json:"edges"`
}

type Episode struct {
	ID        int64       `json:"id"`
	VideoID   int64       `json:"videoID"`
	Num       float64     `json:"num"`
	Title     string      `json:"title"`
	Desc      string      `json:"desc"`
	Cover     string      `json:"cover"`
	URL       string      `json:"url"`
	MobileURL string      `json:"mobileURL"`
	Subtitles []*Subtitle `json:"subtitles"`
	CreatedAt int64       `json:"createdAt"`
	UpdatedAt int64       `json:"updatedAt"`
}

type History struct {
	UID           int64   `json:"uid"`
	SourceType    int64   `json:"sourceType"`
	SourceID      int64   `json:"sourceID"`
	Title         string  `json:"title"`
	Num           int64   `json:"num"`
	SubTitle      string  `json:"subTitle"`
	Cover         string  `json:"cover"`
	SubSourceID   int64   `json:"subSourceID"`
	DeviceType    string  `json:"deviceType"`
	CurrentTime   float64 `json:"currentTime"`
	RemainingTime float64 `json:"remainingTime"`
	UpdatedAt     int64   `json:"updatedAt"`
}

type HistoryConnection struct {
	TotalCount int64      `json:"totalCount"`
	Edges      []*History `json:"edges"`
}

type LoginResponse struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type NewAttributeModel struct {
	DeviceModelID int64  `json:"deviceModelID"`
	Key           string `json:"key"`
	Name          string `json:"name"`
}

type NewDevice struct {
	DeviceModelID int64   `json:"deviceModelID"`
	Name          string  `json:"name"`
	IP            *string `json:"ip"`
	Port          *int64  `json:"port"`
	Username      *string `json:"username"`
	Password      *string `json:"password"`
}

type NewDeviceDashboard struct {
	Name       string `json:"name"`
	IsVisible  bool   `json:"isVisible"`
	DeviceType int64  `json:"deviceType"`
}

type NewDeviceDashboardCamera struct {
	DeviceDashboardID int64   `json:"deviceDashboardID"`
	DeviceIDs         []int64 `json:"deviceIDs"`
}

type NewDeviceDashboardTelemetry struct {
	DeviceDashboardID int64   `json:"deviceDashboardID"`
	TelemetryIDs      []int64 `json:"telemetryIDs"`
}

type NewDeviceModel struct {
	Name          string  `json:"name"`
	Desc          *string `json:"desc"`
	DeviceType    int64   `json:"deviceType"`
	CameraCompany int64   `json:"cameraCompany"`
}

type NewEpisode struct {
	VideoID   int64          `json:"videoID"`
	Num       float64        `json:"num"`
	Title     *string        `json:"title"`
	Desc      *string        `json:"desc"`
	Cover     *string        `json:"cover"`
	URL       string         `json:"url"`
	Subtitles []*NewSubtitle `json:"subtitles"`
}

type NewHistoryInput struct {
	SourceType    int64   `json:"sourceType"`
	SourceID      int64   `json:"sourceID"`
	SubSourceID   int64   `json:"subSourceID"`
	DeviceType    string  `json:"deviceType"`
	CurrentTime   float64 `json:"currentTime"`
	RemainingTime float64 `json:"remainingTime"`
}

type NewSaveSubtitles struct {
	ID        int64         `json:"id"`
	Subtitles *NewSubtitles `json:"subtitles"`
}

type NewSubtitle struct {
	Name string `json:"name"`
	URL  string `json:"url"`
}

type NewSubtitles struct {
	Name string   `json:"name"`
	Urls []string `json:"urls"`
}

type NewTelemetryModel struct {
	DeviceModelID int64   `json:"deviceModelID"`
	Key           string  `json:"key"`
	Name          string  `json:"name"`
	Factor        float64 `json:"factor"`
	Unit          *string `json:"unit"`
	UnitName      *string `json:"unitName"`
	Scale         int64   `json:"scale"`
}

type NewThing struct {
	Name                string   `json:"name"`
	Num                 float64  `json:"num"`
	BrandName           *string  `json:"brandName"`
	Pics                []string `json:"pics"`
	UnitPrice           float64  `json:"unitPrice"`
	Unit                *string  `json:"unit"`
	Specifications      *string  `json:"specifications"`
	Category            int64    `json:"category"`
	ConsumerExpenditure string   `json:"consumerExpenditure"`
	Location            *string  `json:"location"`
	Status              int64    `json:"status"`
	PurchaseDate        int64    `json:"purchaseDate"`
	PurchasePlatform    *string  `json:"purchasePlatform"`
	RefOrderID          *string  `json:"refOrderID"`
	RubbishCategory     []int64  `json:"rubbishCategory"`
}

type NewUpdateAttributeModel struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type NewUpdateDevice struct {
	ID       int64   `json:"id"`
	Name     string  `json:"name"`
	IP       *string `json:"ip"`
	Port     *int64  `json:"port"`
	Username *string `json:"username"`
	Password *string `json:"password"`
}

type NewUpdateDeviceDashboard struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	IsVisible bool   `json:"isVisible"`
}

type NewUpdateDeviceModel struct {
	ID   int64   `json:"id"`
	Name string  `json:"name"`
	Desc *string `json:"desc"`
}

type NewUpdateEpisode struct {
	ID        int64          `json:"id"`
	Num       *float64       `json:"num"`
	Title     *string        `json:"title"`
	Desc      *string        `json:"desc"`
	Cover     *string        `json:"cover"`
	URL       string         `json:"url"`
	Subtitles []*NewSubtitle `json:"subtitles"`
}

type NewUpdateMobileVideos struct {
	ID        int64    `json:"id"`
	VideoURLs []string `json:"videoURLs"`
}

type NewUpdateProfile struct {
	Avatar    *string `json:"avatar"`
	Gender    *int64  `json:"gender"`
	Color     *string `json:"color"`
	BirthDate *int64  `json:"birthDate"`
	IP        *string `json:"ip"`
}

type NewUpdateTelemetryModel struct {
	ID       int64   `json:"id"`
	Name     string  `json:"name"`
	Factor   float64 `json:"factor"`
	Unit     string  `json:"unit"`
	UnitName string  `json:"unitName"`
	Scale    int64   `json:"scale"`
}

type NewUpdateThing struct {
	ID                  int64    `json:"id"`
	Name                *string  `json:"name"`
	Num                 *float64 `json:"num"`
	BrandName           *string  `json:"brandName"`
	Pics                []string `json:"pics"`
	UnitPrice           *float64 `json:"unitPrice"`
	Unit                *string  `json:"unit"`
	Specifications      *string  `json:"specifications"`
	Category            *int64   `json:"category"`
	ConsumerExpenditure *string  `json:"consumerExpenditure"`
	Location            *string  `json:"location"`
	Status              *int64   `json:"status"`
	PurchaseDate        *int64   `json:"purchaseDate"`
	PurchasePlatform    *string  `json:"purchasePlatform"`
	RefOrderID          *string  `json:"refOrderID"`
	RubbishCategory     []int64  `json:"rubbishCategory"`
}

type NewUpdateUser struct {
	ID        int64   `json:"id"`
	Password  *string `json:"password"`
	Avatar    *string `json:"avatar"`
	RoleID    *int64  `json:"roleID"`
	Gender    *int64  `json:"gender"`
	Color     *string `json:"color"`
	BirthDate *int64  `json:"birthDate"`
	IP        *string `json:"ip"`
}

type NewUpdateVideo struct {
	ID      int64    `json:"id"`
	Title   *string  `json:"title"`
	Desc    *string  `json:"desc"`
	PubDate *int64   `json:"pubDate"`
	Cover   *string  `json:"cover"`
	Tags    []string `json:"tags"`
	IsShow  *bool    `json:"isShow"`
	Theme   string   `json:"theme"`
}

type NewUpdateVideoSeries struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type NewUpdateVideoSeriesItem struct {
	VideoSeriesID int64  `json:"videoSeriesID"`
	VideoID       int64  `json:"videoID"`
	Alias         string `json:"alias"`
}

type NewUser struct {
	Name      string  `json:"name"`
	Password  string  `json:"password"`
	Avatar    *string `json:"avatar"`
	RoleID    int64   `json:"roleID"`
	Gender    int64   `json:"gender"`
	BirthDate *int64  `json:"birthDate"`
	IP        *string `json:"ip"`
}

type NewVideo struct {
	Title   string   `json:"title"`
	Desc    *string  `json:"desc"`
	PubDate *int64   `json:"pubDate"`
	Cover   *string  `json:"cover"`
	Tags    []string `json:"tags"`
	IsShow  bool     `json:"isShow"`
	Theme   string   `json:"theme"`
}

type NewVideoResource struct {
	ID        int64    `json:"id"`
	VideoURLs []string `json:"videoURLs"`
}

type NewVideoSeries struct {
	Name string `json:"name"`
}

type NewVideoSeriesItem struct {
	VideoSeriesID int64  `json:"videoSeriesID"`
	VideoID       int64  `json:"videoID"`
	Alias         string `json:"alias"`
}

type PieLineSerieData struct {
	X1 []string  `json:"x1"`
	X2 []string  `json:"x2"`
	Y  []float64 `json:"y"`
}

type SerieData struct {
	Name  string  `json:"name"`
	Value float64 `json:"value"`
}

type Sort struct {
	Field string `json:"field"`
	IsAsc bool   `json:"isAsc"`
}

type Staff struct {
	Job     string   `json:"job"`
	Persons []string `json:"persons"`
}

type Subtitle struct {
	Name string `json:"name"`
	URL  string `json:"url"`
}

type Telemetry struct {
	ID        int64    `json:"id"`
	DeviceID  int64    `json:"deviceID"`
	Key       string   `json:"key"`
	Name      string   `json:"name"`
	Value     *float64 `json:"value"`
	Factor    float64  `json:"factor"`
	Scale     int64    `json:"scale"`
	Unit      string   `json:"unit"`
	UnitName  string   `json:"unitName"`
	CreatedAt int64    `json:"createdAt"`
	UpdatedAt int64    `json:"updatedAt"`
}

type TelemetryModel struct {
	ID            int64   `json:"id"`
	DeviceModelID int64   `json:"deviceModelID"`
	Key           string  `json:"key"`
	Name          string  `json:"name"`
	Factor        float64 `json:"factor"`
	Unit          string  `json:"unit"`
	UnitName      string  `json:"unitName"`
	Scale         int64   `json:"scale"`
	CreatedAt     int64   `json:"createdAt"`
	UpdatedAt     int64   `json:"updatedAt"`
}

type Thing struct {
	ID                  int64    `json:"id"`
	UID                 int64    `json:"uid"`
	Name                string   `json:"name"`
	Num                 float64  `json:"num"`
	BrandName           *string  `json:"brandName"`
	Pics                []string `json:"pics"`
	UnitPrice           float64  `json:"unitPrice"`
	Unit                *string  `json:"unit"`
	Specifications      *string  `json:"specifications"`
	Category            int64    `json:"category"`
	ConsumerExpenditure string   `json:"consumerExpenditure"`
	Location            string   `json:"location"`
	Status              int64    `json:"status"`
	PurchaseDate        int64    `json:"purchaseDate"`
	PurchasePlatform    *string  `json:"purchasePlatform"`
	RefOrderID          string   `json:"refOrderID"`
	RubbishCategory     []int64  `json:"rubbishCategory"`
	CreatedAt           int64    `json:"createdAt"`
	UpdatedAt           int64    `json:"updatedAt"`
}

type ThingConnection struct {
	TotalCount int64    `json:"totalCount"`
	Edges      []*Thing `json:"edges"`
}

type User struct {
	ID        int64   `json:"id"`
	UID       string  `json:"uid"`
	Name      string  `json:"name"`
	Avatar    *string `json:"avatar"`
	RoleID    int64   `json:"roleID"`
	Gender    int64   `json:"gender"`
	Color     *string `json:"color"`
	BirthDate int64   `json:"birthDate"`
	IP        *string `json:"ip"`
	CreatedAt int64   `json:"createdAt"`
	UpdatedAt int64   `json:"updatedAt"`
}

type UserConnection struct {
	TotalCount int64   `json:"totalCount"`
	Edges      []*User `json:"edges"`
}

type Video struct {
	ID        int64      `json:"id"`
	Title     string     `json:"title"`
	Desc      string     `json:"desc"`
	PubDate   int64      `json:"pubDate"`
	Cover     string     `json:"cover"`
	Episodes  []*Episode `json:"episodes"`
	Tags      []string   `json:"tags"`
	IsShow    bool       `json:"isShow"`
	Theme     string     `json:"theme"`
	CreatedAt int64      `json:"createdAt"`
	UpdatedAt int64      `json:"updatedAt"`
}

type VideoConnection struct {
	TotalCount int64    `json:"totalCount"`
	Edges      []*Video `json:"edges"`
}

type VideoIndex struct {
	ID       int64  `json:"id"`
	Title    string `json:"title"`
	Desc     string `json:"desc"`
	Cover    string `json:"cover"`
	TotalNum int64  `json:"totalNum"`
}

type VideoIndexConnection struct {
	TotalCount int64         `json:"totalCount"`
	Edges      []*VideoIndex `json:"edges"`
	AggResults []*AggResult  `json:"aggResults"`
}

type VideoSeries struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Items     []*VideoSeriesItem `json:"items"`
	CreatedAt int64              `json:"createdAt"`
	UpdatedAt int64              `json:"updatedAt"`
}

type VideoSeriesConnection struct {
	TotalCount int64          `json:"totalCount"`
	Edges      []*VideoSeries `json:"edges"`
}

type VideoSeriesItem struct {
	VideoSeriesID int64  `json:"videoSeriesID"`
	VideoID       int64  `json:"videoID"`
	Title         string `json:"title"`
	Alias         string `json:"alias"`
	Num           int64  `json:"num"`
}
