// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Character struct {
	CharacterName string `json:"characterName"`
	OriginalName  string `json:"originalName"`
}

type Episode struct {
	ID        int64  `json:"id"`
	MediaID   int64  `json:"mediaID"`
	Order     int64  `json:"order"`
	Title     string `json:"title"`
	Desc      string `json:"desc"`
	Cover     string `json:"cover"`
	URL       string `json:"url"`
	Subtitle  string `json:"subtitle"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
}

type Media struct {
	ID         int64        `json:"id"`
	Title      string       `json:"title"`
	Desc       string       `json:"desc"`
	PubDate    int64        `json:"pubDate"`
	Cover      string       `json:"cover"`
	Episodes   []*Episode   `json:"episodes"`
	Characters []*Character `json:"characters"`
	Staffs     []*Staff     `json:"staffs"`
	CreatedAt  int64        `json:"createdAt"`
	UpdatedAt  int64        `json:"updatedAt"`
}

type NewCharacter struct {
	CharacterName string `json:"characterName"`
	OriginalName  string `json:"originalName"`
}

type NewEpisode struct {
	MediaID  int64  `json:"mediaID"`
	Order    int64  `json:"order"`
	Title    string `json:"title"`
	Desc     string `json:"desc"`
	Cover    string `json:"cover"`
	URL      string `json:"url"`
	Subtitle string `json:"subtitle"`
}

type NewMedia struct {
	Title      string          `json:"title"`
	Desc       string          `json:"desc"`
	PubDate    int64           `json:"pubDate"`
	Cover      string          `json:"cover"`
	Characters []*NewCharacter `json:"characters"`
	Staffs     []*NewStaff     `json:"staffs"`
}

type NewStaff struct {
	Job     string   `json:"job"`
	Persons []string `json:"persons"`
}

type Staff struct {
	Job     string   `json:"Job"`
	Persons []string `json:"Persons"`
}
